### PR TITLE
Fix list and table print

### LINKED ISSUE #647: colour of table is slightly wrong
image

### PR DESCRIPTION
**Pull request by jntrnr**
fixes #647

### CODE REVIEW

File: crates/nu-parser/src/flatten.rs [hunk 1]
```diff
@@ -44,6 +46,8 @@ impl Display for FlatShape {
             FlatShape::Signature => write!(f, "flatshape_signature"),
             FlatShape::String => write!(f, "flatshape_string"),
             FlatShape::StringInterpolation => write!(f, "flatshape_string_interpolation"),
+            FlatShape::List => write!(f, "flatshape_string_interpolation"),
```
Comment (fdncred) [inline crates/nu-parser/src/flatten.rs:49]: shouldn't list be `flatshape_list`? :)
